replicaCount: 1

image:
  repository: aymanoweis/go-web-app
  pullPolicy: IfNotPresent
  tag: "23986585351"

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: go-web-app.local
      paths:
        - path: /
          pathType: Prefix
